  %% Import data from spreadsheet  
% Script for importing data from the following spreadsheet:
%%
% 
%    Workbook: /MATLAB Drive/ExcelAutomation/Automation_Sample Calender_v0.1.xlsx
%    Worksheet: Simple
% cker 
%% 
% Auto-generated by MATLAB on 20-Jul-2021 09:41:36
%% Set up the Import Options and import the data

 opts = spreadsheetImportOptions("NumVariables", 11);

% Specify sheet and range 
opts.Sheet = "Sample_STEPin";
opts.DataRange = "A4:K100";

% Specify column names and types
opts.VariableNames = ["VarName1", "Date", "Day", "CourseCode", "Module", "Leads", "Leads1", "Leads2", "SessionSlot", "SessionTime", "Comments"];
opts.VariableTypes = ["string", "double", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical"];

% Specify variable properties
opts = setvaropts(opts, "VarName1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["VarName1", "Day", "CourseCode", "Module", "Leads", "Leads1", "Leads2", "SessionSlot", "SessionTime", "Comments"], "EmptyFieldRule", "auto");

% Import the data
Automation_SampleCalender_v0_1 = readtable("Automation_Sample Calender_v0.6.xlsx", opts, "UseExcel", false);
%% Convert to output type

VarName1 = Automation_SampleCalender_v0_1.VarName1;
Date = Automation_SampleCalender_v0_1.Date;
Day = Automation_SampleCalender_v0_1.Day;
CourseCode = Automation_SampleCalender_v0_1.CourseCode;
Module = Automation_SampleCalender_v0_1.Module;
Leads = Automation_SampleCalender_v0_1.Leads;
Leads1 = Automation_SampleCalender_v0_1.Leads1;
Leads2 = Automation_SampleCalender_v0_1.Leads2;
SessionSlot = Automation_SampleCalender_v0_1.SessionSlot;
SessionTime = Automation_SampleCalender_v0_1.SessionTime;
Comments = Automation_SampleCalender_v0_1.Comments;
%% Clear temporary variables

clear Automation_SampleCalender_v0_1 opts
TogetherArray = cat(1,Leads,Leads1,Leads2);
FacultyList = unique(TogetherArray);
FacultyList = rmmissing(FacultyList);
FacultyList = upper(FacultyList);
MSlots = zeros(length(FacultyList),1);
ASlots = zeros(length(FacultyList),1);
Month = "JULY";
Month = upper(Month);
Initiative = "STEPin";
for i=1:length(Leads)
    for j=1:length(FacultyList)
        if(SessionSlot(i)=='M')
            if(Leads(i)==FacultyList(j))
                MSlots(j) = MSlots(j)+1;
            end
            if(Leads1(i)==FacultyList(j))
                MSlots(j) = MSlots(j)+1;
            end
            if(Leads2(i)==FacultyList(j))
                MSlots(j) = MSlots(j)+1;
            end
        elseif(SessionSlot(i)=='A')
            if(Leads(i)==FacultyList(j))
                ASlots(j) = ASlots(j)+1;
            end
            if(Leads1(i)==FacultyList(j))
                ASlots(j) = ASlots(j)+1;
            end
            if(Leads2(i)==FacultyList(j))
                ASlots(j) = ASlots(j)+1;
            end
        elseif(SessionSlot(i)=='F')
            if(Leads(i)==FacultyList(j))
                ASlots(j) = ASlots(j)+1;
                MSlots(j) = MSlots(j)+1;
            end
            if(Leads1(i)==FacultyList(j))
                ASlots(j) = ASlots(j)+1;
                MSlots(j) = MSlots(j)+1;
            end
            if(Leads2(i)==FacultyList(j))
                ASlots(j) = ASlots(j)+1;
                MSlots(j) = MSlots(j)+1;
            end
        end
    end
end
Months =            ["JANUARY","FEBRUARY","MARCH","APRIL","MAY","JUNE","JULY","AUGUST","SEPTEMBER","OCTOBER","NOVEMBER","DECEMBER"];
FacultyRange =      ["B4:B23","B30:B49","B56:B75","B82:B101","B108:B127","B134:B153","B160:B179","B186:B205","B212:B231","B238:B257","B264:B283","B290:B309"];
NumRange =          [4,23,30,49,56,75,82,101,108,127,134,153,160,179,186,205,212,231,238,257,264,283,290,309];
GenesisProgram =    ["C4:D23","C30:D49","C56:D75","C82:D101","C108:D127","C134:D153","C160:D179","C186:D205","C212:D231","C238:D257","C264:D283","C290:D309"];
GenesisProProgram = ["E4:F23","E30:F49","E56:F75","E82:F101","E108:F127","E134:F153","E160:F179","E186:F205","E212:F231","E238:F257","E264:F283","E290:F309"];
BuildProgram =      ["G4:H23","G30:H49","G56:H75","G82:H101","G108:H127","G134:H153","G160:H179","G186:H205","G212:H231","G238:H257","G264:H283","G290:H309"];
OpenProgram =       ["I4:J23","I30:J49","I56:J75","I82:J101","I108:J127","I134:J153","I160:J179","I186:J205","I212:J231","I238:J257","I264:J283","I290:J309"];
StepProgram =       ["K4:L23","K30:L49","K56:L75","K82:L101","K108:L127","K134:L153","K160:L179","K186:L205","K212:L231","K238:L257","K264:L283","K290:L309"];
TeechProgram =      ["M4:N23","M30:N49","M56:N75","M82:N101","M108:N127","M134:N153","M160:N179","M186:N205","M212:N231","M238:N257","M264:N283","M290:N309"];
Others =            ["O4:P23","O30:P49","O56:P75","O82:P101","O108:P127","O134:P153","O160:P179","O186:P205","O212:P231","O238:P257","O264:P283","O290:P309"];
PlannedRange =      ["Q4:R23","Q30:R49","Q56:R75","Q82:R101","Q108:R127","Q134:R153","Q160:R179","Q186:R205","Q212:R231","Q238:R257","Q264:R283","Q290:R309"];
AvailableRange =    ["S4:T23","S30:T49","S56:T75","S82:T101","S108:T127","S134:T153","S160:T179","S186:T205","S212:T231","S238:T257","S264:T283","S290:T309"];
SlotRange =         ["C4:P23","C30:P49","C56:P75","C82:P101","C108:P127","C134:P153","C160:P179","C186:P205","C212:P231","C238:P257","C264:P283","C290:P309"];
WholeRange =        ["B4:P23","B30:P49","B56:P75","B82:P101","B108:P127","B134:P153","B160:P179","B186:P205","B212:P231","B238:P257","B264:P283","B290:P309"];
Slots = cat(2,MSlots,ASlots);
for i=1:12
    if(Month == Months(i))
        index=i;
    end
end
[~,FacultyDow] = xlsread('FacultyLoadSheet_Output.xlsx',1,FacultyRange(index));
lenFac = length(FacultyDow);
CheckList = zeros(length(FacultyList),1);
for i=1:length(FacultyDow)
    for j=1:length(FacultyList)        
        if(FacultyList(j)==FacultyDow(i))
            CheckList(j) = 1;
            if(Initiative == "GENESIS")
                writematrix(MSlots(j),'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',['C',num2str(NumRange(index*2-1)+i-1)]);
                writematrix(ASlots(j),'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',['D',num2str(NumRange(index*2-1)+i-1)]);
            elseif(Initiative == "GENESIS PRO")
                writematrix(MSlots(j),'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',['E',num2str(NumRange(index*2-1)+i-1)]);
                writematrix(ASlots(j),'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',['F',num2str(NumRange(index*2-1)+i-1)]);
            elseif(Initiative == "BUILD / STEP UP")
                writematrix(MSlots(j),'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',['G',num2str(NumRange(index*2-1)+i-1)]);
                writematrix(ASlots(j),'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',['H',num2str(NumRange(index*2-1)+i-1)]);
            elseif(Initiative == "OPEN TRAININGS")
                writematrix(MSlots(j),'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',['I',num2str(NumRange(index*2-1)+i-1)]);
                writematrix(ASlots(j),'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',['J',num2str(NumRange(index*2-1)+i-1)]);
            elseif(Initiative == "STEPin")
                writematrix(MSlots(j),'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',['K',num2str(NumRange(index*2-1)+i-1)]);
                writematrix(ASlots(j),'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',['L',num2str(NumRange(index*2-1)+i-1)]);
            elseif(Initiative == "TEECH PRAAAVINYA")
                writematrix(MSlots(j),'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',['M',num2str(NumRange(index*2-1)+i-1)]);
                writematrix(ASlots(j),'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',['N',num2str(NumRange(index*2-1)+i-1)]);
            elseif(Initiative == "OTHERS")
                writematrix(MSlots(j),'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',['O',num2str(NumRange(index*2-1)+i-1)]);
                writematrix(ASlots(j),'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',['P',num2str(NumRange(index*2-1)+i-1)]);
            end
        end
    end
end
if(isempty(FacultyDow))
  writematrix(FacultyList,'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',FacultyRange(index));
  if(Initiative == "GENESIS")
      writematrix(Slots,'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',GenesisProgram(index));
  elseif(Initiative == "GENESIS PRO")
      writematrix(Slots,'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',GenesisProProgram(index));
  elseif(Initiative == "BUILD / STEP UP")
      writematrix(Slots,'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',BuildProgram(index));
  elseif(Initiative == "OPEN TRAINING")
      writematrix(Slots,'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',OpenProgram(index));
  elseif(Initiative == "STEPin")
      writematrix(Slots,'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',StepProgram(index));
  elseif(Initiative == "TEECH PRAAAVINYA")
      writematrix(Slots,'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',TeechProgram(index));
  elseif(Initiative == "OTHERS")
      writematrix(Slots,'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',Others(index));
  end  
end
k = -1;
if(~isempty(FacultyDow))
    for j=1:length(FacultyList)
        if(CheckList(j)==0)
            k = k + 1;
            writematrix(FacultyList(j),'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',['B',num2str(NumRange(index*2-1)+lenFac+k)]);
            if(Initiative == "GENESIS")
                writematrix(MSlots(j),'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',['C',num2str(NumRange(index*2-1)+lenFac+k)]);
                writematrix(ASlots(j),'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',['D',num2str(NumRange(index*2-1)+lenFac+k)]);
            elseif(Initiative == "GENESIS PRO")
                writematrix(MSlots(j),'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',['E',num2str(NumRange(index*2-1)+lenFac+k)]);
                writematrix(ASlots(j),'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',['F',num2str(NumRange(index*2-1)+lenFac+k)]);
            elseif(Initiative == "BUILD / STEP UP")
                writematrix(MSlots(j),'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',['G',num2str(NumRange(index*2-1)+lenFac+k)]);
                writematrix(ASlots(j),'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',['H',num2str(NumRange(index*2-1)+lenFac+k)]);
            elseif(Initiative == "OPEN TRAININGS")
                writematrix(MSlots(j),'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',['I',num2str(NumRange(index*2-1)+lenFac+k)]);
                writematrix(ASlots(j),'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',['J',num2str(NumRange(index*2-1)+lenFac+k)]);
            elseif(Initiative == "STEPin")
                writematrix(MSlots(j),'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',['K',num2str(NumRange(index*2-1)+lenFac+k)]);
                writematrix(ASlots(j),'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',['L',num2str(NumRange(index*2-1)+lenFac+k)]);
            elseif(Initiative == "TEECH PRAAAVINYA")
                writematrix(MSlots(j),'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',['M',num2str(NumRange(index*2-1)+lenFac+k)]);
                writematrix(ASlots(j),'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',['N',num2str(NumRange(index*2-1)+lenFac+k)]);
            elseif(Initiative == "OTHERS")
                writematrix(MSlots(j),'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',['O',num2str(NumRange(index*2-1)+lenFac+k)]);
                writematrix(ASlots(j),'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',['P',num2str(NumRange(index*2-1)+lenFac+k)]);
            end
        end
    end
end
[~,UpFacultyList] = xlsread('FacultyLoadSheet_Output.xlsx',1,FacultyRange(index));
PlannedSlots = zeros(length(UpFacultyList),2);
AvailableSlots = zeros(length(UpFacultyList),2);
for i = 1:length(UpFacultyList)
    for j = 1:2
        PlannedSlots(i,j) = 18;
    end
end
Slots = xlsread('FacultyLoadSheet_Output.xlsx',1,SlotRange(index));
Slots(isnan(Slots))=0;
for i=1:length(UpFacultyList)
    writematrix(PlannedSlots(i,1),'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',['Q',num2str(NumRange(index*2-1)+i-1)]);
    writematrix(PlannedSlots(i,2),'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',['R',num2str(NumRange(index*2-1)+i-1)]);
    AvailableSlots(i,1) = PlannedSlots(i,1) - sum(Slots(i,1:2:end));
    AvailableSlots(i,2) = PlannedSlots(i,2) - sum(Slots(i,2:2:end));
    writematrix(AvailableSlots(i,1),'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',['S',num2str(NumRange(index*2-1)+i-1)]);
    writematrix(AvailableSlots(i,2),'FacultyLoadSheet_Output.xlsx','Sheet',1,'Range',['T',num2str(NumRange(index*2-1)+i-1)]);
end
